<?php

namespace WebStoreBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemUsedRepository extends \Doctrine\ORM\EntityRepository
{
}
