app:
    resource: '@WebStoreBundle/Controller/'
    type: annotation

user_registration:
    path: /register
    defaults: { _controller: WebStoreBundle:Register:register }

logout:
    path: /logout